import Form from "../components/form/Form";
import Layout from "../components/layout/Layout";
import Head from "next/dist/shared/lib/head";
import Heading from "../components/Heading";

export default function contact() {
	return (
		<>
			<Layout>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Heading title="Contact us"></Heading>
				<Form />
			</Layout>
		</>
	);
}
