import Layout from "../../components/layout/Layout";
import Head from "next/dist/shared/lib/head";
import Heading from "../../components/Heading";
import axios from "axios";
import { BASE_URL } from "../api/country";
import { DateTime } from "luxon";

export default function detail({ post }) {
	console.log(post);

	return (
		<Layout>
			<Head>
				<title>{post.title.rendered}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Heading title={`${post.title.rendered}`}></Heading>
			<p>Date: {DateTime.fromISO(`${post.date}`).toFormat(`dd LLL yyyy`)}</p>
			<div dangerouslySetInnerHTML={{ __html: post.excerpt.rendered }} />
		</Layout>
	);
}

export async function getStaticPaths() {
	try {
		const response = await axios.get(BASE_URL);
		console.log(response.data);

		const posts = response.data;

		const path = posts.map((post) => ({
			params: { id: post.id.toString() },
		}));

		return {
			paths: path,
			fallback: false,
		};
	} catch (error) {
		console.log(error);
	}
}

export async function getStaticProps({ params }) {
	let post = null;
	const url = `${BASE_URL}/${params.id}`;

	const response = await axios.get(url);
	post = response.data;

	return {
		props: {
			post: post,
		},
	};
}
